<?php
/**
 * Created by PhpStorm.
 * User: mxj
 * Date: 2018/2/11
 * Time: 下午4:56
 */

namespace Diduweiwu\Papollo\Facades;


use Illuminate\Support\Facades\Facade;

class PapolloFacade extends Facade
{
    protected static function getFacadeAccessor()
    {
        return "apolloclient"; // TODO: Change the autogenerated stub
    }
}